using System.Collections.Generic;
using UnityEngine;

/// <summary>Ngân hàng câu hỏi cho <see cref="LessonQuizCampaign15PackGenerator"/>.</summary>
internal static class QuizQuestionBank
{
    public static List<LessonQuizQuestion> BuildEveningQuestions(int day)
        => PickFive(EveningSeeds(day), day, light: true);

    public static List<LessonQuizQuestion> BuildClassQuestions(int day, bool mid, bool fin)
    {
        int seed = day * 31 + (mid ? 919 : 0) + (fin ? 727 : 0);
        return PickFive(ClassSeeds(seed, mid, fin), day, light: false);
    }

    static List<LessonQuizQuestion> PickFive(IReadOnlyList<SeedQ> seeds, int day, bool light)
    {
        var list = new List<LessonQuizQuestion>(5);
        int n = seeds.Count;
        int start = (day * 17 + 3) % Mathf.Max(1, n - 4);
        for (int k = 0; k < 5; k++)
        {
            SeedQ s = seeds[(start + k) % n];
            list.Add(s.ToQuestion(day, light));
        }

        return list;
    }

    readonly struct SeedQ
    {
        readonly string _p;
        readonly string _a;
        readonly string _b;
        readonly string _c;
        readonly string _d;
        readonly int _ok;

        public SeedQ(string p, string a, string b, string c, string d, int ok)
        {
            _p = p;
            _a = a;
            _b = b;
            _c = c;
            _d = d;
            _ok = ok;
        }

        public LessonQuizQuestion ToQuestion(int day, bool light)
        {
            string p = _p.Replace("{d}", day.ToString());
            return new LessonQuizQuestion
            {
                prompt = light ? $"[Ôn chơi — ngày {day}] {p}" : $"[Lớp — ngày {day}] {p}",
                options = new List<string> { _a, _b, _c, _d },
                correctIndex = _ok,
                explanation = string.Empty
            };
        }
    }

    static IReadOnlyList<SeedQ> EveningSeeds(int day)
    {
        // Lộn xộn theo ngày: vẫn vui, không "liên quan game" bắt buộc.
        var r = new List<SeedQ>(BaseEvening);
        if (day % 3 == 0)
        {
            r.Add(new SeedQ(
                "Sinh viên huyền thoại thức đêm thường để làm gì?",
                "Viết CV dài 40 trang",
                "Tạo bug rồi đổ thừa compile",
                "Ngủ trưa 3 tiếng để bù",
                "Ăn mì rồi thề mai đổi đời",
                3));
        }

        if (day % 4 == 0)
        {
            r.Add(new SeedQ(
                "Chọn một 'chiến lược' ôn bài hợp pháp duy nhất:",
                "Đọc slide trên giường cho tới khi... ngủ",
                "Lập mindmap bằng meme",
                "Giải thích bài cho mèo",
                "Pomodoro 25p + nghỉ 6 tiếng",
                0));
        }

        return r;
    }

    static IReadOnlyList<SeedQ> ClassSeeds(int seed, bool mid, bool fin)
    {
        var r = new List<SeedQ>(BaseClass);
        if (mid)
        {
            r.AddRange(MidtermExtra);
        }

        if (fin)
        {
            r.AddRange(FinalExtra);
        }

        // Xáo trộn nhẹ theo seed (không cần Fisher–Yates đầy đủ)
        int off = seed % r.Count;
        if (off > 0)
        {
            var rot = r.GetRange(off, r.Count - off);
            rot.AddRange(r.GetRange(0, off));
            r = rot;
        }

        return r;
    }

    static readonly SeedQ[] BaseEvening =
    {
        new("Nếu deadline là 'con ma', cách xử lý đúng kiểu chill là gì?",
            "Rủ ma uống trà sữa rồi thương lượng gia hạn",
            "Giả vờ mất mạng 5 năm",
            "In slide ra đắp chăn",
            "Tạo group chat tên 'Mai Làm'",
            0),
        new("Tối nay bạn 'học' kiểu nào là hợp lý nhất (theo nghĩa hài hước)?",
            "Học bằng cách xem review 0.5x",
            "Học bằng nghe nhạc lo-fi + suy ngẫm vũ trụ",
            "Học bằng lướt feed '5 phút' (4 giờ)",
            "Học bằng viết TODO rồi hoàn thành... TODO",
            1),
        new("Món ăn nào được coi là 'vật phẩm buff năng lượng' khi cú đêm?",
            "Mì tôm + trứng + tội lỗi",
            "Salad (trong tưởng tượng)",
            "Nước lọc 'tinh khiết' từ máy lọc bị quên thay lõi",
            "Kẹo cao su vị deadline",
            0),
        new("Khi bạn mở sách ra mà não mở YouTube, đó gọi là?",
            "Hiện tượng song song đa vũ trụ",
            "Multitasking 'thất bại đẹp'",
            "Tính năng tự động của Gen Z",
            "Lỗi người dùng, không phải lỗi phần mềm",
            1),
        new("Chọn câu 'triết học' đúng nhất cho sinh viên:",
            "Tôi ngủ sớm để mai dậy sớm (nói từ 2h sáng)",
            "Tôi không trì hoãn, tôi chỉ tối ưu… thời gian tương lai",
            "Tôi làm xong hết, chỉ là chưa bắt đầu",
            "Tôi học bằng trực giác (trực giác bảo ngủ)",
            2),
        new("Tại sao highlight màu vàng lại 'dễ nhớ'?",
            "Vì não thích màu xám của thực tại",
            "Vì highlighter hết mực nhanh nên não buồn quên",
            "Vì giáo viên cũng thích vàng",
            "Vì đó là skill skin premium",
            0),
        new("Bạn 'ôn' bằng cách nào sau đây là… tệ nhưng thật?",
            "Đọc lại dòng đầu slide 40 lần",
            "Kể lại bài cho bạn cùng phòng… đang ngủ",
            "Thu âm giọng mình rồi không bao giờ nghe lại",
            "Tất cả đều có thể xảy ra",
            3),
        new("Nếu GPA là boss game, vũ khí meta là gì?",
            "Đi học đúng giờ + nộp bài đúng hạn",
            "Skin laptop RGB",
            "Nick name 'tryhard' trên Discord",
            "Ảnh avatar cú đêm",
            0),
        new("Một 'nhiệm vụ phụ' hợp lý tối nay là gì?",
            "Dọn bàn (để mai lại bừa)",
            "Tưới cây… trên wallpaper",
            "Sắp xếp file Desktop thành một file tên 'sau này'",
            "Backup dữ liệu (ý thức)",
            3),
        new("Tại sao 'mai làm' lại viral?",
            "Vì nó miễn phí",
            "Vì nó scale tốt",
            "Vì nó có community support mạnh",
            "Vì deadline là illusion",
            2),
        new("Chọn phát biểu 'đúng tinh thần' sinh viên:",
            "Tôi chỉ cần 10 phút (×24)",
            "Tôi làm nhanh khi… đã muộn",
            "Tôi học theo batch — mỗi học kỳ một batch",
            "Tôi không stress, stress là… bạn thân",
            1),
        new("Khi não bạn bảo 'đói kiến thức' nhưng miệng bảo 'đói mì', bạn làm gì?",
            "Thỏa hiệp: học một chương, ăn một gói",
            "Giả vờ đọc chương 1 trong khi húp mì",
            "Đăng story than thở",
            "Tất cả đều ổn",
            0),
        new("Vì sao lịch báo '{d}' lại căng?",
            "Vì có chữ '{d}'",
            "Vì thời gian không wait",
            "Vì messenger hay ping",
            "Vì cosmic radiation",
            1),
        new("Tối đẹp nhất của sinh viên là tối nào?",
            "Tối không học nhưng tự tin",
            "Tối học 20 phút rồi tự reward 2 tiếng",
            "Tối… vẫn là tối",
            "Tối có snack",
            3),
        new("Đâu là 'skill' không nằm trong syllabus nhưng lại học được?",
            "Đọc lướt PDF 400 trang",
            "Viết mail xin deadline kiểu professional",
            "Ngụy trang tab YouTube thành Google Docs",
            "Tất cả đều rất meta",
            3),
        new("Quiz chill: Emoji nào mô tả đúng tâm trạng trước kỳ thi?",
            "🙂",
            "🫠",
            "🦄",
            "📈 (ảo tưởng)",
            1),
        new("Một meme học đường 'đạo đức' là gì?",
            "Chia sẻ tài liệu cho bạn… sau khi nhận mì",
            "Tag bạn vào deadline",
            "Nhắn 'tụi mình chết' rồi ai cũng ổn",
            "Ăn team rank… ý là ăn team project",
            2),
        new("Nếu stress là thanh máu, thanh nào 'sai build'?",
            "Luôn full nhưng vẫn combat",
            "Luôn 1% nhưng vẫn tự tin",
            "Luôn 50% vì 'cân bằng'",
            "Ẩn thanh — vì denial",
            3),
        new("Cách 'reset' sau một ngày dài tệ nhất là gì?",
            "Tắm + nhạc + không mở mail",
            "Ngủ và mơ thấy điểm A",
            "Đặt báo thức 'ngày mai mới là thứ Hai'",
            "Uống nước (thật)",
            0),
        new("Chọn 'thuyết âm mưu' hợp lý nhất:",
            "Deadline được thiết kế để test lòng tin",
            "Wi-Fi chậm khi cần nộp bài",
            "Ổ cứng hay đầy đúng lúc quan trọng",
            "Tất cả đều có thể true cùng lúc",
            3),
        new("Tối nay bạn chọn theme học tập nào?",
            "Dark mode + cà phê + self doubt",
            "Light mode + nước lọc + toxic positivity",
            "Sepia + jazz + vintage suffering",
            "RGB + EDM + I'm fine",
            0),
        new("Câu nào là 'lời hứa' an toàn nhất?",
            "Mai mình dậy sớm (có bằng chứng)",
            "Tối nay mình làm xong (không định nghĩa 'xong')",
            "Mình chỉ xem 1 video (YouTube đồng ý)",
            "Mình ngủ sớm (2h sáng là sớm so với 5h sáng)",
            3),
        new("Nếu trí nhớ là RAM, sinh viên thường có bao nhiêu GB?",
            "16GB nhưng cache đầy meme",
            "32GB nhưng swap sang điện thoại",
            "8GB nhưng Chrome",
            "Không đo được — random access",
            2),
        new("Khi bạn nói 'hiểu rồi' nhưng mắt trống rỗng, nghĩa là?",
            "Bạn hiểu… phần đầu câu",
            "Bạn hiểu vibe",
            "Bạn hiểu là phải hỏi lại",
            "Bạn hiểu life",
            2),
        new("Chọn 'boss' khó nhất trong đời sinh viên:",
            "Môn có 3 đồ án + 2 quiz + 1 vibe check",
            "Tìm chỗ ngồi ở thư viện",
            "Hiểu đề bài",
            "Tất cả boss đều scale theo tuần",
            3),
        new("Tại sao highlighter hồng lại nguy hiểm?",
            "Vì nó quá đẹp nên bạn highlight cả… cảm xúc",
            "Vì giáo viên không thích màu hồng",
            "Vì hồng là warning color",
            "Vì nó làm bạn tưởng mình đã học",
            3),
        new("Một 'chiêu' tránh procrastination (phiên bản meme) là gì?",
            "Đặt báo thức tên 'Sợ thầy'",
            "Đổi tên Wi-Fi thành 'Làm bài đi'",
            "Mở Word trước khi mở TikTok (hy vọng)",
            "Tất cả đều… có thể thử",
            3),
        new("Khi bạn học nhóm online, biến cố nào hay nhất?",
            "Quên unmute khi chửi đề",
            "Share nhầm màn hình tab shopping",
            "Cat walk qua keyboard",
            "Tất cả đều oscar-worthy",
            3),
        new("Chọn 'power-up' thực tế nhất:",
            "Nước + ngủ đủ + chia nhỏ việc",
            "Nước tăng lực vị… lo lắng",
            "Podcast 3x speed",
            "Đổi avatar thành mode serious",
            0),
        new("Tối nay bạn xứng đáng reward nào (vui)?",
            "1 tập phim 'dài 5 phút'",
            "Scroll 10 phút (40 phút)",
            "Ăn món yêu thích",
            "Tất cả — theo chế độ 'balance'",
            2),
        new("Một câu 'kinh điển' trước khi thi là gì?",
            "Ôi dễ mà (nghe alarm trong đầu)",
            "Chỉ cần đọc lại phần… toàn bộ",
            "Tụi nó cũng chưa học (tụi nó học rồi)",
            "Mình ổn (đang không ổn)",
            3),
    };

    static readonly SeedQ[] BaseClass =
    {
        new("Logic: Nếu mọi A đều B, và B không phải C, kết luận nào có thể đúng?",
            "Một số A có thể không phải C",
            "Mọi A chắc chắn là C",
            "Không A nào là B",
            "Mọi C đều là A",
            0),
        new("Một tập hợp có 10 phần tử phân biệt. Số tập con có đúng 2 phần tử là bao nhiêu?",
            "45",
            "90",
            "1024",
            "20",
            0),
        new("Xác suất độc lập: P(A)=0.3, P(B)=0.4. P(A∩B) bằng?",
            "0.12",
            "0.7",
            "0.1",
            "0.34",
            0),
        new("Mệnh đề phủ định của 'Mọi x, nếu P(x) thì Q(x)' (trong logic cổ điển) thường được hiểu là:",
            "Tồn tại x sao cho P(x) đúng và Q(x) sai",
            "Không x nào thỏa P(x)",
            "Mọi x, P(x) sai",
            "Tồn tại x, Q(x) sai",
            0),
        new("Trong một dãy số hình học công bội r>0, nếu u1>0 và r>1 thì dãy:",
            "Tăng ngặt",
            "Giảm ngặt",
            "Hội tụ về 0",
            "Bị chặn trên bởi u1",
            0),
        new("Một hàm f liên tục trên [a,b] và f(a)f(b)<0. Khẳng định nào đúng (giả sử thực phân tích cơ bản)?",
            "Tồn tại c∈(a,b) sao cho f(c)=0",
            "f đạo hàm mọi nơi",
            "f là đa thức",
            "f có cực đại tuyệt đối tại a",
            0),
        new("Nếu một ma vuông A khả nghịch, phát biểu nào luôn đúng?",
            "det(A) ≠ 0",
            "A^2 = I",
            "A đối xứng",
            "Mọi phần tử A đều dương",
            0),
        new("Thuật ngữ 'p-value' (nhập môn) gần với ý nghĩa nào nhất khi diễn giải đơn giản?",
            "Xác suất (hoặc tương tự) quan sát thấy dữ liệu cực đoan như vậy nếu giả thuyết null đúng",
            "Xác suất giả thuyết null đúng",
            "Độ lệch chuẩn",
            "Sai số đo lường tuyệt đối",
            0),
        new("Chọn câu đúng về 'độ lệch chuẩn' mẫu (thống kê cơ bản):",
            "Đơn vị giống đơn vị dữ liệu gốc",
            "Luôn âm",
            "Bằng phương sai",
            "Không nhạy với outliers",
            0),
        new("'Big-O O(n)' thường mô tả điều gì?",
            "Giới hạn tiệm cận tốc độ tăng thời gian theo kích thước input",
            "Bộ nhớ chính xác tính bằng byte",
            "Số vòng lặp tối đa luôn = n",
            "Độ phức tạp tối thiểu của mọi thuật toán",
            0),
        new("Trong lập trình, 'race condition' gần nghĩa là gì?",
            "Kết quả phụ thuộc thứ tự/timing thực thi không kiểm soát",
            "Chạy code trên CPU quá nhanh",
            "Lỗi cú pháp",
            "Thiếu RAM",
            0),
        new("HTTP status 404 thường nghĩa là gì?",
            "Không tìm thấy tài nguyên",
            "Lỗi máy chủ nội bộ",
            "Không được phép",
            "Quá nhiều request",
            0),
        new("JSON hợp lệ thường là loại dữ liệu nào?",
            "Cây cú pháp (object/array/string/number/bool/null)",
            "Bảng 2 cột duy nhất",
            "Chuỗi nhị phân không đọc được",
            "Định dạng ảnh",
            0),
        new("OOP: 'đa hình' (polymorphism) gần với ý nào nhất?",
            "Cùng một interface, nhiều lớp thể hiện hành vi khác nhau",
            "Ẩn dữ liệu bằng private",
            "Kế thừa nhiều lớp cha trong C# (mặc định)",
            "Biên dịch AOT",
            0),
        new("Trong C#, 'async/await' chủ yếu phục vụ mục tiêu nào?",
            "Viết bất đồng bộ dễ đọc hơn mà không chặn thread một cách lãng phí",
            "Tăng tốc CPU single-thread tuyệt đối",
            "Thay thế GC",
            "Biến mọi hàm thành song song hoàn hảo",
            0),
        new("Khái niệm 'idempotency' trong API thường nhắm tới điều gì?",
            "Gọi lặp lại một thao tác không làm thay đổi trạng thái thêm lần nữa (ý tưởng)",
            "Mã hóa mật khẩu",
            "Luôn trả 200 OK",
            "Không cần authentication",
            0),
        new("Một chương trình có vòng lặp vô hạn do điều kiện sai. Lỗi gần loại nào nhất?",
            "Logic / lỗi thuật toán điều khiển",
            "Lỗi cú pháp parse",
            "Lỗi linker",
            "Lỗi permission file",
            0),
        new("Trong thiết kế DB, 'khóa ngoại' (foreign key) nhằm…",
            "Ràng buộc tham chiếu giữa bảng",
            "Tăng tốc sort RAM",
            "Mã hóa cột",
            "Tạo index tự động mọi trường hợp",
            0),
        new("SQL: 'JOIN' dùng để làm gì?",
            "Kết hợp hàng từ nhiều bảng theo điều kiện",
            "Xóa bảng",
            "Tạo user",
            "Backup",
            0),
        new("Chọn mệnh đề đúng về 'version control' (Git, ý tưởng):",
            "Commit lưu snapshot lịch sử để quay lui/merge",
            "Branch luôn làm mất code",
            "Merge không bao giờ conflict",
            "Remote luôn trùng local",
            0),
        new("Một yêu cầu phần mềm 'SMART' thường nhấn mạnh tiêu chí nào?",
            "Cụ thể, đo được, khả thi (và các tiêu chí tương tự)",
            "Luôn mơ hồ để linh hoạt",
            "Không cần deadline",
            "Không cần stakeholder",
            0),
        new("Rủi ro dự án: 'mitigation' gần nghĩa là gì?",
            "Giảm xác suất/tác động",
            "Tăng rủi ro để nhanh",
            "Bỏ qua rủi ro",
            "Chuyển rủi ro cho người dùng mà không thông báo",
            0),
        new("Trong quản lý thời gian, 'Pomodoro' cổ điển thường là:",
            "25 phút tập trung + nghỉ ngắn",
            "90 phút liên tục",
            "5 phút làm 5 phút nghỉ vô hạn",
            "Học đến khi ngất",
            0),
        new("Tư duy phản biện: 'nguồn tin cậy' nên ưu tiên điều gì?",
            "Bằng chứng có thể kiểm chứng, xuất xứ rõ",
            "Chữ IN HOA trên Facebook",
            "Nhiều emoji hơn",
            "Cảm xúc mạnh hơn",
            0),
        new("Một lập luận 'ad hominem' là gì?",
            "Tấn công người thay vì tấn công luận điểm",
            "Dùng số liệu",
            "Dùng ví dụ tương tự",
            "Hỏi ngược lại đúng trọng tâm",
            0),
        new("Chọn câu đúng về 'bias' trong thống kê/học máy (nhập môn):",
            "Mô hình có thể học sai hệ thống do dữ liệu/ giả định",
            "Bias luôn bằng 0 nếu dùng GPU",
            "Bias chỉ xảy ra khi vẽ biểu đồ",
            "Bias là lỗi cú pháp",
            0),
        new("Nếu một mạng máy tính dùng HTTPS, ý chính là gì?",
            "Kênh được mã hóa (TLS) giữa client và server (ý tưởng)",
            "Không cần DNS",
            "Không thể bị tấn công",
            "Luôn nhanh hơn HTTP",
            0),
        new("Khái niệm 'CAP' (tóm tắt) trong hệ phân tán thường nhấn mạnh điều gì?",
            "Có sự đánh đổi giữa consistency/availability/partition tolerance trong thực tế",
            "Luôn đạt cả 3 hoàn hảo",
            "Chỉ áp dụng cho SQL",
            "Không liên quan microservices",
            0),
        new("Một 'unit test' tốt thường:",
            "Nhanh, độc lập, lặp lại được, kiểm tra đơn vị nhỏ",
            "Luôn cần mạng",
            "Luôn chạy production DB",
            "Không cần assert",
            0),
        new("Refactor an toàn thường đi kèm gì?",
            "Test/lint + thay đổi nhỏ từng bước",
            "Xóa hết code cũ một lần",
            "Không cần review",
            "Không cần build",
            0),
        new("Chọn phát biểu đúng về 'regular expression' (regex) trong thực hành:",
            "Hữu ích nhưng dễ phức tạp — cần kiểm thử mẫu",
            "Luôn O(1)",
            "Thay thế parser mọi ngôn ngữ",
            "Không bao giờ backtracking",
            0),
        new("Trong UI/UX, 'affordance' gần nghĩa là gì?",
            "Gợi ý cách dùng qua hình dạng/nhãn",
            "Số lượng màu tối đa",
            "FPS",
            "Độ phân giải texture",
            0),
        new("'Accessibility' (a11y) trong game/app thường nhắm tới:",
            "Người dùng có nhu cầu khác nhau (thị giác/thính giác/điều khiển…)",
            "Chỉ dark mode",
            "Chỉ font size",
            "Chỉ marketing",
            0),
        new("Một 'deadlock' (OS) xảy ra khi nào (ý tưởng)?",
            "Các tiến trình chờ lẫn nhau theo vòng kín tài nguyên",
            "CPU quá nhanh",
            "RAM = 0",
            "Chỉ xảy ra trên Linux",
            0),
        new("Trong Unity, 'FixedUpdate' thường phù hợp cho:",
            "Vật lý bước cố định (ý tưởng)",
            "Vẽ UI layout mỗi frame",
            "Load scene bất đồng bộ",
            "Gọi API HTTP",
            0),
        new("Chọn câu đúng về 'serialization' (lưu trữ trạng thái):",
            "Chuyển object thành dạng có thể lưu/chuyển rồi khôi phục (ý tưởng)",
            "Luôn an toàn mà không cần versioning",
            "Không bao giờ lỗi schema",
            "Chỉ JSON",
            0),
        new("Một 'buffer overflow' (ý tưởng lịch sử) liên quan gì?",
            "Ghi vượt vùng đệm dẫn tới hành vi không an toàn",
            "Lỗi Wi-Fi",
            "Lỗi đồ họa",
            "Lỗi build iOS",
            0),
        new("Trong mật mã học nhập môn, 'hash một chiều' thường được kỳ vọng:",
            "Khó đảo ngược từ digest về input (ý tưởng)",
            "Giải mã bằng khóa công khai",
            "Luôn có độ dài vô hạn",
            "Thay thế mã hóa đối xứng mọi nơi",
            0),
        new("Chọn phát biểu gần đúng nhất về 'NP-hard' (chỉ nói chuyện ý tưởng):",
            "Lớp bài toán 'khó' — thường gắn tối ưu hóa tổ hợp",
            "Luôn giải được trong O(n)",
            "Chỉ trong game",
            "Không liên quan CS",
            0),
        new("Một 'memory leak' trong C# managed thường liên quan gì (thực tế)?",
            "Giữ reference không cần thiết tới đối tượng lớn/event",
            "GC không tồn tại",
            "Stack overflow",
            "NullReference mọi lúc",
            0),
        new("Trong song song hóa, 'mutex' thường dùng để:",
            "Đảm bảo đoạn critical không bị xen kẽ không kiểm soát",
            "Tăng FPS",
            "Tải asset",
            "Serialize JSON nhanh hơn",
            0),
        new("Chọn câu đúng về 'technical debt' (nợ kỹ thuật):",
            "Hy sinh chất lượng tạm thời để tốc độ — trả lãi sau",
            "Luôn tốt",
            "Không ảnh hưởng maintenance",
            "Chỉ xảy ra ở startup",
            0),
    };

    static readonly SeedQ[] MidtermExtra =
    {
        new("GK: Một bài toán tối ưu 'knapsack 0/1' cổ điển thường được giải bằng:",
            "Quy hoạch động",
            "Duy nhất tham lam luôn tối ưu",
            "DFS không nhớ",
            "Random walk",
            0),
        new("GK: Độ phức tạp trung bình của tìm kiếm trên BST cân bằng (ý tưởng) gần:",
            "O(log n)",
            "O(1) mọi lúc",
            "O(n^2)",
            "O(2^n)",
            0),
        new("GK: Trong SQL, 'transaction' nhằm:",
            "Nhóm thao tác ACID (ý tưởng)",
            "Tăng độ phân giải",
            "Render shader",
            "Build APK",
            0),
        new("GK: 'Overfitting' trong ML thường nghĩa là:",
            "Khớp nhiễu tập train quá mức, kém khái quát",
            "Khớp quá ít",
            "Luôn tốt hơn underfitting",
            "Không liên quan validation",
            0),
        new("GK: 'Recursion' cần điều kiện gì để tránh vô hạn (ý tưởng)?",
            "Base case + tiến tới base",
            "Chỉ cần return",
            "Chỉ cần vòng for",
            "Không cần",
            0),
    };

    static readonly SeedQ[] FinalExtra =
    {
        new("CK: Trong thiết kế hệ thống, 'eventual consistency' gần nghĩa:",
            "Sau đủ thời gian/thao tác, các bản sao hội tụ (ý tưởng)",
            "Luôn nhất quán tức thì mọi lúc",
            "Không bao giờ nhất quán",
            "Chỉ cho database SQL",
            0),
        new("CK: 'SLA' thường là cam kết về:",
            "Mức dịch vụ/uptime/latency theo hợp đồng (ý tưởng)",
            "Số dòng code",
            "Số bug mong muốn",
            "RGB case",
            0),
        new("CK: 'Rate limiting' trong API nhằm:",
            "Giới hạn tần suất request để bảo vệ hệ thống",
            "Tăng unlimited traffic",
            "Thay thế auth",
            "Render mesh",
            0),
        new("CK: 'Zero trust' (an ninh) gần với ý:",
            "Không tin mặc định bên trong ranh giới — xác minh liên tục (ý tưởng)",
            "Tin tưởng mọi USB",
            "Tắt firewall",
            "Chia sẻ private key",
            0),
        new("CK: Một 'chaotic system' (ý tưởng) thường có tính:",
            "Nhạy điều kiện đầu (butterfly effect)",
            "Luôn dự đoán dài hạn dễ",
            "Luôn tuần hoàn đơn giản",
            "Không phụ thuộc tham số",
            0),
    };
}
